name: Run Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: playwright install --with-deps
      - run: pytest
      - run: npm install -g newman
      - run: newman run "QA_Practice.postman_collection.json" -e "Dev.postman_environment.json"